version: "3.3"
services:
  python_server:
    image: "python:3.11-slim-buster"
    expose:
      - "4200"
    command: "python -m http.server 4200"
    networks:
      - keycloak_network

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    command: [ "start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=${KC_DB_USERNAME}
      - DB_PASSWORD=${KC_DB_PASSWORD}
      - OAUTH2_REDIRECT_URI=http://localhost:8080/oidc/auth/code
      - OAUTH2_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH2_ISSUER=https://accounts.google.com
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    ports:
      - "8082:8080"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - keycloak_network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge

volumes:
  postgres_data:
