version: "3.3"
services:
  python_server:
    image: "python:3.11-slim-buster"

    expose:
      - "8081"
    command: "python -m http.server 4200"
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      splash_auth_network:

  splash_auth:
    container_name: splash_auth
    #image: ghcr.io/als-computing/splash_auth:main
    build: 
      context: ..
    # command: sleep 99999
    command: uvicorn splash_auth.main:app --proxy-headers --host 0.0.0.0 --port 8000 --log-level=debug --use-colors --reload
    environment:
    - OAUTH_AUTH_ENDPOINT=https://accounts.google.com/o/oauth2/v2/auth
    - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
    - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
    - OAUTH_REDIRECT_URI=http://localhost:8080/oidc/auth/code
    - OAUTH_TOKEN_URI=https://oauth2.googleapis.com/token
    - OUATH_JWKS_URI=https://www.googleapis.com/oauth2/v3/certs
    - TOKEN_EXP_TIME=172400
    - JWT_SECRET=${JWT_SECRET}
    - OUATH_SUCCESS_REDIRECT_URI=http://localhost:8080/
    - OUATH_FAIL_REDIRECT_URI=http://localhost:8080
    - HTTPX_LOG_LEVEL=trace
    volumes:
    - ../:/app
    - ./users.yml:/app/users.yml
    - ./api_keys.yml:/app/api_keys.yml
    restart: unless-stopped
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    networks:
      splash_auth_network:
networks:
  splash_auth_network:
    driver: bridge
